gridaco/grida

web/index-dev.html
web/index-hash.html
web/index.html

https://user-images.githubusercontent.com/40719546/107883994-b5dc5e00-6f35-11eb-8b44-f11c0b202bf9.mov
Change Indicator Ui, "Loading Bar"

Change Style Web Indicator

---

README.md
chrome-extension/manifest.json
chrome-extension/surf.gist.github.js
chrome-extension/surf.github.js
extensions/githubsurf/src/api.ts
extensions/githubsurf/src/githubsurffs.ts

New platform Support, "GIST"

---

extensions/githubsurf/src/api.ts
extensions/githubsurf/src/githubsurffs.ts

[GITLAB DEMO](https://gitlab.surf/abdellah.abdellah707/moon/blob/HEAD/moon.md)
- Gitlab Support!

modify : new platform supprot, gitlab

---

chrome-extension/surf.github.js

**Before**
**After**
- Change Button Image 🏄‍♂️ -> 🏄‍
#14

modify : change imoge, issue fix #14

---

extensions/githubsurf/src/api.ts
extensions/githubsurf/src/githubsurffs.ts

Reverts surfcodes/surf#21
Unknown bug appears after Gitlab platform additional update

Revert "modify : new platform supprot, gitlab"

---

extensions/githubsurf/src/api.ts
extensions/githubsurf/src/githubsurffs.ts

Problems with Gitlab's API, the path part of the API that calls up Repo is the path of the root directory, not the path of the current directory.
It is as follows.
**response structure where bugs occur**
```
A
ㄴ A/B
ㄴ A/B/C
```
**Modified response structure**
```
A
ㄴ B
ㄴ C
```
> In the case of Map type, the key value is put in the get function and the variable is imported. I sent the request to b, but it was actually a problem because there was no b but a/b.

fix : not load directory

---

apps/forms/app/(d)/d/[id]/data/layout.tsx
apps/forms/app/(d)/d/[id]/layout.tsx
apps/forms/app/(site)/[project_name]/page.tsx
apps/forms/app/(site)/dashboard/route.ts
apps/forms/components/toaster/index.tsx
apps/forms/components/ui/command.tsx
apps/forms/package.json
apps/forms/scaffolds/editor/action.ts
apps/forms/scaffolds/editor/editor.tsx
apps/forms/scaffolds/editor/reducer.ts
apps/forms/scaffolds/editor/state.ts
apps/forms/scaffolds/grid-editor/index.tsx
apps/forms/scaffolds/grid/grid.tsx
apps/forms/scaffolds/panels/customer-panel.tsx
apps/forms/scaffolds/panels/field-edit-panel.tsx
apps/forms/scaffolds/settings/custom-page-background-preferences.tsx
apps/forms/scaffolds/settings/custom-section-style-preferences.tsx
apps/forms/scaffolds/settings/ending-page-preferences.tsx
pnpm-lock.yaml

- max toast
- fix grid layout
- settings select clear
- customer panel wip

Forms - daily update

---

apps/forms/app/(api)/submit/[id]/route.ts
apps/forms/app/(d)/d/[id]/connect/store/get-started/page.tsx
apps/forms/app/(d)/d/[id]/connect/store/products/page.tsx
apps/forms/app/(d)/d/route.ts
apps/forms/components/beta/comming-soon-overlay.tsx
apps/forms/scaffolds/e/form/index.tsx
apps/forms/scaffolds/panels/field-edit-panel.tsx
apps/forms/services/commerce/index.ts
apps/forms/services/form/validate-max-access.ts
apps/forms/types/supabase.ts

- block alpha features
- inventory committed value rpc
- multi submit prevention on built in agent

Forms - inventory committed value rpc

---

apps/forms/app/(api)/v1/[id]/route.ts
apps/forms/app/(d)/d/e/[id]/alreadyresponded/page.tsx
apps/forms/components/ui/collapsible.tsx
apps/forms/k/i18n.ts
apps/forms/package.json
apps/forms/scaffolds/e/form/index.tsx
apps/forms/services/form/validate-max-access.ts
pnpm-lock.yaml

- already responded page with cs support data (customer id)

Forms - Daily release

---

apps/forms/app/(api)/v1/[id]/route.ts
apps/forms/k/error.ts
apps/forms/scaffolds/e/form/index.tsx
apps/forms/services/customer/index.ts

This resolves https://github.com/gridaco/grida/issues/85

Forms - fix #85 (infinite loading)

---

apps/forms/app/(api)/embed/[id]/route.tsx
apps/forms/app/(api)/private/editor/customers/[uid]/route.ts
apps/forms/app/(d)/d/[id]/layout.tsx
apps/forms/components/copy-to-clipboard-input/index.tsx
apps/forms/components/preferences/index.tsx
apps/forms/components/ui/avatar.tsx
apps/forms/lib/supabase/client.ts
apps/forms/lib/supabase/server.ts
apps/forms/package.json
apps/forms/scaffolds/editor/action.ts
apps/forms/scaffolds/editor/editor.tsx
apps/forms/scaffolds/editor/reducer.ts
apps/forms/scaffolds/grid/grid.tsx
apps/forms/scaffolds/panels/customer-panel.tsx
apps/forms/scaffolds/settings/closing-preference.tsx
apps/forms/scaffolds/settings/custom-page-background-preferences.tsx
apps/forms/scaffolds/settings/custom-powered-by-branding-preferences.tsx
apps/forms/scaffolds/settings/custom-section-style-preferences.tsx
apps/forms/scaffolds/settings/data-dynamic-field-preferences.tsx
apps/forms/scaffolds/settings/ending-page-preferences.tsx
apps/forms/scaffolds/settings/ending-redirect-preferences.tsx
apps/forms/scaffolds/settings/form-page-language-preferences.tsx
apps/forms/scaffolds/settings/response-preferences.tsx
apps/forms/scaffolds/settings/trusted-origin-preferences.tsx
apps/forms/types/index.ts
apps/forms/types/supabase.ts
pnpm-lock.yaml

- customer panel on response row
- ui improvments in settings page

Forms - Daily release - customer panel & ui improvements

---

apps/forms/app/(api)/private/editor/fields/route.ts
apps/forms/components/form-field-type-icon.tsx
apps/forms/components/formfield/form-field-preview.tsx
apps/forms/components/formfield/use-safe-select-value.ts
apps/forms/components/ui/slider.tsx
apps/forms/k/supported_field_types.ts
apps/forms/package.json
apps/forms/scaffolds/blocks-editor/blocks/field-block.tsx
apps/forms/scaffolds/e/form/index.tsx
apps/forms/scaffolds/grid/grid.tsx
apps/forms/scaffolds/mediapicker/index.tsx
apps/forms/scaffolds/options/options-edit.tsx
apps/forms/scaffolds/panels/field-edit-panel.tsx
apps/forms/types/index.ts
apps/forms/types/supabase.ts
pnpm-lock.yaml

- slider (range)
- switch (checkbox)
- options with src
- radio
- select
- checkboxes

Forms - Daily release options with image

---

apps/forms/app/(dev)/playground/page.tsx
apps/forms/public/schema/examples/form.example.json
apps/forms/public/schema/field.schema.json
apps/forms/public/schema/form.schema.json
apps/forms/public/schema/option.schema.json
apps/forms/types/index.ts

form json schema pub
- https://forms.grida.co/schema/form.schema.json

Forms schema

---

apps/forms/app/(api)/v1/[id]/route.ts
apps/forms/app/(dev)/playground/page.tsx
apps/forms/lib/forms/index.ts
apps/forms/lib/forms/renderer.ts
apps/forms/package.json
apps/forms/public/schema/field.schema.json
apps/forms/public/schema/form.schema.json
apps/forms/scaffolds/e/form/index.tsx
apps/forms/types/index.ts
apps/forms/types/schema.ts
pnpm-lock.yaml

https://forms.grida.co/playground

Forms - form schema & renderer

---

apps/forms/app/(dev)/playground/publish/route.ts
apps/forms/app/(site)/dashboard/route.ts
apps/forms/lib/forms/renderer.ts
apps/forms/lib/forms/url.ts
apps/forms/scaffolds/e/form/index.tsx
apps/forms/scaffolds/playground/playground.tsx
apps/forms/services/new/json2db.ts
apps/forms/types/schema.ts

Forms - Publish your playground

---

apps/forms/app/(api)/v1/[id]/export/csv/route.ts
apps/forms/app/(d)/d/e/[id]/complete/page.tsx
apps/forms/app/(theme)/templates/embed/[lng]/formcomplete/receipt01/page.tsx
apps/forms/scaffolds/editor/editor.tsx
apps/forms/scaffolds/grid-editor/index.tsx
apps/forms/scaffolds/grid/grid.tsx
apps/forms/scaffolds/grid/types.ts
apps/forms/scaffolds/panels/customer-panel.tsx
apps/forms/scaffolds/panels/response-edit-panel.tsx
apps/forms/theme/templates/formcomplete/receipt01.tsx
apps/forms/theme/templates/formcomplete/types.ts
apps/forms/types/supabase.ts
apps/forms/types/types.ts
apps/forms/utils/fmt.ts

[migration] grida_forms.response local_id -> local_index

[migration] grida_forms.response local_id -> local_index

---

apps/forms/app/(dev)/playground/page.tsx
apps/forms/app/(dev)/playground/publish/route.ts
apps/forms/components/formfield/form-field.tsx
apps/forms/lib/forms/renderer.ts
apps/forms/public/schema/examples/005-logics/form.json
apps/forms/public/schema/examples/005-logics/form.v2.json
apps/forms/scaffolds/blocks-editor/blocks-editor.tsx
apps/forms/scaffolds/blocks-editor/blocks/field-block.tsx
apps/forms/scaffolds/e/form/core/action.ts
apps/forms/scaffolds/e/form/core/agent.tsx
apps/forms/scaffolds/e/form/core/dispatch.ts
apps/forms/scaffolds/e/form/core/provider.tsx
apps/forms/scaffolds/e/form/core/reducer.ts
apps/forms/scaffolds/e/form/core/state.ts
apps/forms/scaffolds/e/form/formview.tsx
apps/forms/scaffolds/e/form/use-logical.tsx
apps/forms/scaffolds/editor/action.ts
apps/forms/scaffolds/editor/editor.tsx
apps/forms/scaffolds/editor/reducer.ts
apps/forms/scaffolds/editor/state.ts
apps/forms/scaffolds/panels/block-edit-panel.tsx
apps/forms/scaffolds/playground/k.ts
apps/forms/scaffolds/playground/playground.tsx
apps/forms/scaffolds/playground/preview/index.tsx
apps/forms/services/new/json2db.ts
apps/forms/types/logic.ts
apps/forms/types/schema.ts
apps/forms/types/supabase.ts
apps/forms/types/types.ts
apps/forms/types/utility.ts

https://github.com/gridaco/grida/assets/16307013/e521b984-5145-4ad4-8242-749274c30bf2

Forms - Logical Blocks

---

apps/forms/app/(api)/submit/[id]/route.ts
apps/forms/app/(api)/v1/[id]/route.ts
apps/forms/app/(d)/d/[id]/data/simulator/page.tsx
apps/forms/app/(d)/d/e/[id]/formclosed/page.tsx
apps/forms/k/errcode.ts
apps/forms/k/error.ts
apps/forms/k/system.ts
apps/forms/lib/ipinfo/index.ts
apps/forms/lib/simulator/index.ts
apps/forms/scaffolds/blocks-editor/blocks/field-block.tsx
apps/forms/services/form/inventory.ts
apps/forms/types/supabase.ts
apps/forms/types/types.ts
apps/forms/utils/qs.ts

https://github.com/gridaco/grida/assets/16307013/c10adecd-c7f4-4606-9d19-833a019c1e0f

Grida Forms - Strict Access Control w/db constraints

---

apps/forms/app/(api)/private/editor/settings/form-method/route.ts
apps/forms/app/(api)/v1/[id]/route.ts
apps/forms/app/(d)/d/[id]/settings/general/page.tsx
apps/forms/lib/forms/unwrap.ts
apps/forms/scaffolds/blocks-editor/blocks/field-block.tsx
apps/forms/scaffolds/e/form/index.tsx
apps/forms/scaffolds/editor/action.ts
apps/forms/scaffolds/editor/reducer.ts
apps/forms/scaffolds/grid/grid.tsx
apps/forms/scaffolds/settings/form-method-preference.tsx
apps/forms/types/supabase.ts
apps/forms/types/types.ts

https://github.com/gridaco/grida/assets/16307013/bbc72ddc-a56f-4cdb-81ac-85bbba75f571

Forms - Form Method preference

---

apps/forms/app/(api)/submit/[id]/hooks.ts
apps/forms/app/(api)/submit/[id]/hooks/clearsession/route.ts
apps/forms/app/(api)/submit/[id]/route.ts
apps/forms/app/(api)/v1/[id]/route.ts
apps/forms/app/(d)/d/[id]/layout.tsx
apps/forms/components/formfield/form-field.tsx
apps/forms/lib/forms/rawdata.ts
apps/forms/lib/forms/unwrap.ts
apps/forms/scaffolds/editor/action.ts
apps/forms/scaffolds/editor/reducer.ts
apps/forms/scaffolds/editor/state.ts
apps/forms/scaffolds/editor/symbols.ts
apps/forms/scaffolds/grid-editor/index.tsx
apps/forms/scaffolds/grid/grid.tsx
apps/forms/scaffolds/grid/types.ts

https://github.com/gridaco/grida/assets/16307013/9f621be2-389c-40cd-90fd-a18811bd17da

[Day 59] Forms - Table Time

---

apps/forms/lib/forms/unwrap.ts
apps/forms/scaffolds/editor/state.ts
apps/forms/scaffolds/grid-editor/index.tsx
apps/forms/scaffolds/grid/grid.tsx
apps/forms/scaffolds/grid/mask.ts

[Day 60] Forms - data masking

---

apps/forms/app/(api)/submit/[id]/hooks.ts
apps/forms/app/(api)/submit/[id]/hooks/postindexing/route.ts
apps/forms/app/(api)/submit/[id]/route.ts
apps/forms/app/(d)/d/[id]/data/customers/[customer_id]/page.tsx
apps/forms/app/(d)/d/[id]/data/customers/page.tsx
apps/forms/app/(d)/d/[id]/data/responses/page.tsx
apps/forms/app/(dev)/dev/supabase/migrations/002-index-customer/route.ts
apps/forms/database.types.ts
apps/forms/package.json
apps/forms/scaffolds/analytics/world/live-world-analytics.tsx
apps/forms/scaffolds/d/tabs.tsx
apps/forms/scaffolds/grid-editor/index.tsx
apps/forms/scaffolds/grid/customer-grid.tsx
apps/forms/scaffolds/panels/customer-panel.tsx
apps/forms/scaffolds/sidebar/sidebar.tsx
apps/forms/services/customer/utils.ts
apps/forms/types/types.ts
apps/forms/utils/unique.ts
pnpm-lock.yaml

- new layout
- customer info indexing based on inferable response data
https://github.com/gridaco/grida/assets/16307013/a79b2778-0413-414d-9b68-f6c7afc54218

Forms - Layout 2.0

---

apps/forms/app/(api)/private/editor/[form_id]/fields/route.ts
apps/forms/app/(api)/submit/[id]/meta.ts
apps/forms/app/(api)/submit/[id]/route.ts
apps/forms/app/(api)/submit/[id]/sbconn.ts
apps/forms/components/copy-to-clipboard-input/index.tsx
apps/forms/components/formfield/form-field.tsx
apps/forms/components/richtext/styles.css
apps/forms/database.types.ts
apps/forms/k/supported_field_types.ts
apps/forms/k/system.ts
apps/forms/lib/forms/gfkeys.ts
apps/forms/lib/forms/renderer.ts
apps/forms/public/schema/field.schema.json
apps/forms/scaffolds/e/form/formview.tsx
apps/forms/scaffolds/editor/editor.tsx
apps/forms/scaffolds/grid-editor/grid-data.ts
apps/forms/scaffolds/grid/file-cell.tsx
apps/forms/scaffolds/grid/response-grid.tsx
apps/forms/scaffolds/grid/types.ts
apps/forms/scaffolds/panels/field-edit-panel.tsx
apps/forms/services/form/utils.ts
apps/forms/types/schema.ts
apps/forms/types/types.ts

Forms - datetime-local tz support

---

apps/forms/app/(api)/private/accounts/organizations/[org]/delete/route.ts
apps/forms/app/(api)/private/accounts/organizations/[org]/profile/route.ts
apps/forms/app/(api)/private/accounts/organizations/[org]/projects/check-name/route.ts
apps/forms/app/(api)/private/accounts/organizations/[org]/projects/new/route.ts
apps/forms/app/(api)/private/accounts/organizations/check-name/route.ts
apps/forms/app/(d)/[org]/layout.tsx
apps/forms/app/(d)/[org]/new-project-dialog.tsx
apps/forms/app/(d)/[org]/org-menu.tsx
apps/forms/app/(d)/[org]/page.tsx
apps/forms/app/(site)/organizations/[organization_name]/route.ts
apps/forms/app/(site)/organizations/[organization_name]/settings/profile/delete.tsx
apps/forms/app/(site)/organizations/[organization_name]/settings/profile/page.tsx
apps/forms/app/(site)/organizations/[organization_name]/settings/route.ts
apps/forms/app/(site)/organizations/new/page.tsx
apps/forms/components/sidebar/index.tsx
apps/forms/database.types.ts
apps/forms/services/utils/username.ts
apps/forms/types/types.ts

**Towards General Availability - Pt.2**

Forms - GA - Manage Organization & Create Project

---

apps/forms/app/(d)/[org]/[project_name]/page.tsx
apps/forms/app/(d)/[org]/page.tsx
apps/forms/app/(d)/d/[id]/blocks/page.tsx
apps/forms/app/(d)/d/[id]/data/customers/page.tsx
apps/forms/app/(d)/d/[id]/data/responses/page.tsx
apps/forms/components/form-blcok-type-icon.tsx
apps/forms/components/form-field-type-icon.tsx
apps/forms/components/resource-type-icon.tsx
apps/forms/components/sidebar/index.tsx
apps/forms/components/sidenav/sidenav-item.tsx
apps/forms/components/site/form-card.tsx
apps/forms/k/supported_block_types.ts
apps/forms/k/supported_field_types.ts
apps/forms/scaffolds/blocks-editor/new-block-button.tsx
apps/forms/scaffolds/editor/action.ts
apps/forms/scaffolds/editor/editor.tsx
apps/forms/scaffolds/editor/reducer.ts
apps/forms/scaffolds/editor/state.ts
apps/forms/scaffolds/panels/field-edit-panel.tsx
apps/forms/scaffolds/sidebar/sidebar.tsx

Blocks Sidebar
https://github.com/gridaco/grida/assets/16307013/e5a0c0b6-6c04-48f8-b077-706f8b9c8114

Grida Forms - Blocks Sidebar UX

---

apps/forms/app/(api)/private/editor/settings/form-method/route.ts
apps/forms/app/(api)/private/editor/settings/page-font-family/route.ts
apps/forms/app/(api)/private/editor/settings/unknown-fields/route.ts
apps/forms/app/(d)/d/[id]/connect/layout.tsx
apps/forms/app/(d)/d/[id]/settings/customize/page.tsx
apps/forms/app/(d)/d/[id]/settings/general/page.tsx
apps/forms/app/(d)/d/[id]/settings/layout.tsx
apps/forms/app/(d)/d/[id]/settings/security/page.tsx
apps/forms/app/(e)/d/e/[id]/layout.tsx
apps/forms/components/preferences/index.tsx
apps/forms/components/sidebar/index.tsx
apps/forms/components/sidenav/sidenav-badge.tsx
apps/forms/scaffolds/settings/custom-page-css-preference.tsx
apps/forms/scaffolds/settings/custom-page-font-family-preference.tsx
apps/forms/scaffolds/settings/custom-page-palette-preference.tsx
apps/forms/scaffolds/settings/custom-section-style-preferences.tsx
apps/forms/scaffolds/settings/scheduling-preference.tsx
apps/forms/scaffolds/sidebar/sidebar.tsx
apps/forms/theme/templates/formcomplete/receipt01.tsx
apps/forms/types/types.ts

**Choose font family between sans-serif, serif and mono.**
- Inter (sans-serif)
- lora (serif)
- inconsolata (mono)
https://github.com/gridaco/grida/assets/16307013/956035c0-9d8f-41a8-99f3-0c8506982d03

Grida Forms - Themes / Font Family

---

apps/forms/app/(api)/private/editor/settings/page-custom-css/route.ts
apps/forms/app/(api)/v1/[id]/route.ts
apps/forms/app/(d)/d/[id]/layout.tsx
apps/forms/app/(d)/d/[id]/settings/customize/page.tsx
apps/forms/app/(e)/d/e/[id]/layout.tsx
apps/forms/scaffolds/settings/custom-page-background-preferences.tsx
apps/forms/scaffolds/settings/custom-page-css-preference.tsx

**Fully customize your forms' look with custom css 🧑‍💻**
https://github.com/gridaco/grida/assets/16307013/48b2d630-afdd-4dca-9d3a-d29911711ca5

Griad Forms - Themes / Custom CSS

---

apps/forms/components/extension/search-input.tsx
apps/forms/components/formfield/reference-search-field/reference-search-field.tsx
apps/forms/components/highlight/index.tsx
apps/forms/scaffolds/editor/state.ts
apps/forms/scaffolds/grid-editor/grid-data.ts
apps/forms/scaffolds/grid-editor/index.tsx
apps/forms/scaffolds/grid-filter/index.ts
apps/forms/scaffolds/grid/response-grid.tsx

local search in table with fuse & filters

Grida Forms - table local search

---

apps/forms/app/(api)/private/editor/connect/[form_id]/supabase/table/[table_id]/query/route.ts
apps/forms/lib/supabase-postgrest/builder.ts
apps/forms/lib/supabase-postgrest/postgrest-query.ts
apps/forms/scaffolds/editor/action.ts
apps/forms/scaffolds/editor/feed.tsx
apps/forms/scaffolds/editor/reducer.ts
apps/forms/scaffolds/editor/state.ts
apps/forms/scaffolds/grid-editor/index.tsx
apps/forms/scaffolds/grid/response-grid.tsx
apps/forms/types/types.ts

https://github.com/user-attachments/assets/7c0236ff-f9e6-4549-882f-348f3a4c6355

x-supabase `orderby`

---

apps/forms/app/(api)/submit/[id]/route.ts
apps/forms/app/(api)/submit/[id]/sbconn.ts
apps/forms/app/(e)/d/e/[id]/complete/page.tsx
apps/forms/components/formfield/form-field.tsx
apps/forms/database.types.ts
apps/forms/k/supported_field_types.ts
apps/forms/scaffolds/grid/response-grid.tsx
apps/forms/scaffolds/options/options-edit.tsx
apps/forms/scaffolds/panels/field-edit-panel.tsx
apps/forms/scaffolds/sidebar/sidebar-mode-blocks.tsx
apps/forms/services/form/utils.test.ts
apps/forms/services/form/utils.ts
apps/forms/theme/templates/formcomplete/default.tsx

- `toggle-group` support with experimental array value support
- works with external datasource supabase - x-supabase connection
https://github.com/user-attachments/assets/b8fb4259-1ecd-4612-b7ec-d95e7085a0a6

New Field - `toggle-group` (Chips) with experimental array value support

---

apps/forms/app/(site)/maintenance/page.tsx
apps/forms/components/maintenance.tsx
apps/forms/middleware.ts
apps/forms/package.json
pnpm-lock.yaml

Maintenance mode w/vercel edge config

Maintenance mode

---

apps/forms/grida-canvas/action.ts
apps/forms/grida-canvas/domapi.ts
apps/forms/grida-canvas/math.ts
apps/forms/grida-canvas/provider.tsx
apps/forms/grida-canvas/reducers/document.reducer.ts
apps/forms/grida-canvas/reducers/index.ts
apps/forms/grida-canvas/reducers/surface.reducer.ts
apps/forms/grida-canvas/renderer.tsx
apps/forms/grida-canvas/types.ts
apps/forms/grida/index.ts
apps/forms/scaffolds/playground-canvas/playground.tsx

https://github.com/user-attachments/assets/bf856c66-048a-443b-9ccd-914446764f14

Canvas Surface Drawing Mode

---

CONTRIBUTING.md
apps/forms/app/(api)/private/editor/new/route.ts
apps/forms/app/(workbench)/[org]/[proj]/[id]/canvas/page.tsx
apps/forms/app/(workbench)/[org]/[proj]/[id]/data/(data)/page.tsx
apps/forms/app/(workbench)/[org]/[proj]/[id]/layout.tsx
apps/forms/components/resource-type-icon.tsx
apps/forms/database.types.ts
apps/forms/grida-react-canvas/toolbar/index.ts
apps/forms/grida/index.ts
apps/forms/k/labels.ts
apps/forms/lib/forms/url.ts
apps/forms/lib/supabase/client.ts
apps/forms/lib/supabase/server.ts
apps/forms/scaffolds/editor/action.ts
apps/forms/scaffolds/editor/editor.tsx
apps/forms/scaffolds/editor/init.ts
apps/forms/scaffolds/editor/state.ts
apps/forms/scaffolds/playground-canvas/error-boundary.jsx
apps/forms/scaffolds/playground-canvas/playground.tsx
apps/forms/scaffolds/playground-canvas/toolbar.tsx
apps/forms/scaffolds/sidebar/sidebar-mode-design.tsx
apps/forms/scaffolds/sidebar/sidebar.tsx
apps/forms/scaffolds/sidecontrol/index.tsx
apps/forms/scaffolds/sidecontrol/sidecontrol-doctype-form.tsx
apps/forms/scaffolds/sidecontrol/sidecontrol-doctype-site.tsx
apps/forms/scaffolds/sidecontrol/sidecontrol-selected-node.tsx
apps/forms/scaffolds/workspace/create-new-document-button/create-document-button.tsx
apps/forms/services/new/index.ts
apps/forms/tailwind.config.ts
apps/forms/types/types.ts

Wrapper around https://github.com/gridaco/grida/pull/213

Grida Canvas - Initial Release

---

apps/forms/app/(dev)/canvas/tools/ruler/page.tsx
apps/forms/grida-react-canvas/action.ts
apps/forms/grida-react-canvas/provider.tsx
apps/forms/grida-react-canvas/reducers/document.reducer.ts
apps/forms/grida-react-canvas/reducers/event-target.reducer.ts
apps/forms/grida-react-canvas/reducers/history.ts
apps/forms/grida-react-canvas/reducers/methods/transform.ts
apps/forms/grida-react-canvas/reducers/surface.reducer.ts
apps/forms/grida-react-canvas/reducers/tools/snap.ts
apps/forms/grida-react-canvas/state.ts
apps/forms/grida-react-canvas/viewport/context.ts
apps/forms/grida-react-canvas/viewport/hotkeys.tsx
apps/forms/grida-react-canvas/viewport/surface-hooks.ts
apps/forms/grida-react-canvas/viewport/surface.tsx
apps/forms/grida-react-canvas/viewport/ui/rule.tsx
apps/forms/grida-react-canvas/viewport/ui/snap.tsx
apps/forms/package.json
packages/grida-canvas-ruler/component.tsx
packages/grida-canvas-ruler/index.ts
packages/grida-canvas-ruler/package.json
packages/grida-canvas-ruler/ruler.ts
packages/grida-cmath/_snap.ts
packages/grida-cmath/index.ts
pnpm-lock.yaml

`cf194` Grida Canvas - Ruler

---

editor/app/(www)/(contact)/contact/page.tsx
editor/app/(www)/(forms)/header.tsx
editor/www/data/sitemap.ts
editor/www/footer-with-cta.tsx
editor/www/footer.tsx
editor/www/header.tsx

`ryu1` [WWW] Add contact page

---

editor/grida-canvas/reducers/index.ts

- recursively clone nodes when duplicating scenes
- `pnpm turbo test`

Fix scene duplication to deep copy nodes

---

.github/workflows/test.yml

- set up a `Test` workflow
- `pnpm test`

Add CI workflow for tests
